# Cloudflare Pages Configuration
name = "cracked-dev-o-meter"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "frontend"
watch_dir = "src"

[build.environment_variables]
NODE_VERSION = "18"

# Pages Functions (for API routes)
[[pages_build_output]]
# This tells Pages to use functions for API routes
functions = true

# Environment variables for the build
[env.production.vars]
VITE_API_URL = "https://api.cracked-dev-o-meter.workers.dev"
VITE_STRIPE_PUBLISHABLE_KEY = "pk_live_your_publishable_key_here"

[env.preview.vars]
VITE_API_URL = "https://api.cracked-dev-o-meter-preview.workers.dev"
VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_your_publishable_key_here"
