# Cloudflare Workers Configuration
name = "cracked-dev-o-meter-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
DATA_DIR = "/tmp"
MAX_REQUESTS_PER_MIN = "30"
MAX_INPUT_LENGTH = "100"
ENABLE_CORS = "true"
REQUEST_TIMEOUT = "15s"

# KV namespace for user data (alternative to SQLite)
[[kv_namespaces]]
binding = "USER_DATA"
id = "your_kv_namespace_id"

# D1 database for user tracking
[[d1_databases]]
binding = "USER_DB"
database_name = "cracked-dev-o-meter-users"
database_id = "your_d1_database_id"

# Routes
[[routes]]
pattern = "api.cracked-dev-o-meter.workers.dev/*"
zone_name = "your-domain.com"

# Development environment
[env.preview]
name = "cracked-dev-o-meter-api-preview"

[env.preview.vars]
NODE_ENV = "development"

[env.preview.routes]
pattern = "api-preview.cracked-dev-o-meter.workers.dev/*"
zone_name = "your-domain.com"
